Semmle/lgtm-jira-addon

pom.xml, src/main/java/com/semmle/jira/addon/LgtmServlet.java
This PR uses the predefined HTTP status code constants of HttpServletResponse. 
In addition I added some repository declarations and a workaround for a dependency that is no longer available in any public maven repositories. This makes the project much more easy to work with in eclipse.
@nickfyson @Daverlo
=> Make pom more standalone, and use predefined constants for HTTP status codes

src/main/java/com/semmle/jira/addon/config/ProcessedConfig.java
We should only set `priorityLevel` set  if the configured priority is not `null` and not `empty` .
@nickfyson @Daverlo
=> Fix condition for checking whether priority is set or not

pom.xml
This causes the GSON library to be included in the addon jar.
See also: https://developer.atlassian.com/server/framework/atlassian-sdk/managing-dependencies/#using-third-party-code
=> Add scope 'compile' to GSON dependency

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java
Fix the status code to be 500 when no valid transition found (404 only makes sense when the ticket itself was not found).
FYI @aibaars
=> Fix the status code to be 500 when no valid transition found

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/config/init/PluginEnabledHandler.java, src/main/java/com/semmle/jira/addon/config/init/WorkflowResolution.java, src/main/java/com/semmle/jira/addon/config/init/WorkflowUtils.java, src/main/resources/workflow/resolutions.json, src/main/resources/workflow/workflow.xml
This pull request:
* adds support for automatically mapping and creating Resolutions.
* adds update resolution field post-functions to the transitions of
the workflow.
=> Add post-functions that update the resolution field

src/main/resources/admin.vm, src/main/resources/css/lgtm-addon.css, src/main/resources/js/lgtm-addon.js, src/main/resources/lgtm-addon.properties
This PR changes the add-on config page, making it clearer for users which pieces of information come from where. We adopt the terminology `Tracker endpoint` and `LGTM endpoint` and use the same on LGTM itself, meaning that fields which should contain the same value are identically named.
FYI @aibaars @Daverlo @Semmle/doc
=> Improve usability of the add-on config page

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/util/Constants.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestLgtmServletBase.java
* Remove hardcoded name of 'confirmed false positive' status
* Allow transition to be aborted by Validator function
* Add Validator to avoid running the LGTM.Suppress transition if the issue is already in a suppressed state
=>  Remove hardcoded name of 'confirmed false positive' status

pom.xml, src/main/java/com/semmle/jira/addon/JsonError.java, src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/Request.java, src/main/java/com/semmle/jira/addon/Response.java, src/main/java/com/semmle/jira/addon/Util.java, src/main/java/com/semmle/jira/addon/config/init/PluginEnabledHandler.java, src/main/java/com/semmle/jira/addon/config/init/WorkflowResolution.java, src/main/java/com/semmle/jira/addon/config/init/WorkflowStatus.java, src/main/java/com/semmle/jira/addon/config/init/WorkflowUtils.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunction.java, src/test/java/com/semmle/jira/addon/Json.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestLgtmServletBase.java, src/test/java/com/semmle/jira/addon/TestValidateRequest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
The Jackson packages are exported by the system bundle. In addition
the [IssueInputParameters](https://docs.atlassian.com/software/jira/docs/api/7.2.1/com/atlassian/jira/issue/IssueInputParameters.html#addProperty-java.lang.String-org.codehaus.jackson.JsonNode-) interface directly depends on jackson's JsonNode. For our
use-cases both Gson and Jackson are fine. Dropping Gson would remove
a dependency.
=> Remove Gson dependency

src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/resources/js/lgtm-addon.js
This PR adds an informative error message when a manual migration is needed.
I'd hoped to link directly to the workflow scheme for the chosen project, but there doesn't seem to a way to get that ID from the Rest API. Instead users will need to select the appropriate scheme from a list.
Feedback appreciated on whether it all makes sense!
FYI @aibaars @Daverlo @Semmle/doc
=> Add detailed error message when manual migration needed

pom.xml, src/main/java/com/semmle/jira/addon/config/AdminServlet.java, src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/java/com/semmle/jira/addon/util/workflow/WorkflowUtils.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
We had a problem with an exception during plugin install:
```
Upgrade error: Unexpected exception caught during plugin upgrade: com.atlassian.jira.exception.DataAccessException: A status with the name 'In Review' already exists.
at com.atlassian.jira.config.DefaultStatusManager.createStatus(DefaultStatusManager.java:69)
at com.semmle.jira.addon.util.workflow.WorkflowUtils.getOrCreateStatus(WorkflowUtils.java:259)
at com.semmle.jira.addon.util.workflow.WorkflowUtils.updateStatuses(WorkflowUtils.java:130)
```
I rewrote the exists-check in `getOrCreateStatus` method to match the one in the code that would throw the exception. I'm not sure why `ConstantsManager::getIssueConstantByName` did not always work.
In addition this PR cleans up some entries in the pom.xml file and removes `@Scanned` …
=> Fix status already exists exception

src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties
This PR changes the module names and descriptions that are shown when the `8 of 8 modules enabled` link is expanded.
@nickfyson
=> Improve names and descriptions of plugin modules

pom.xml
For some reason declaring the spring scanner annotation packages as imported results in dependency resolution errors for Jira 7.1 and below. We don't actually seem to need those packages at runtime, so it seems safe to declare them as "optional".
=> No longer rely on imported spring scanner annotation packages

lgtm/java-queries/JiraCoreDependency.ql
We should avoid depending directly on the implementation details
of jira-core. Instead we should use the components exposed through
the API.
@Daverlo @nickfyson
=> Query to flag-up direct dependencies on jira-core

src/main/java/com/semmle/jira/addon/util/JiraUtils.java
@nickfyson This should make the behaviour the same as calling the `getSource(Plugin)` method.
=> Include 'plugin:' prefix in managed item source

src/main/java/com/semmle/jira/addon/util/workflow/WorkflowUtils.java, src/main/resources/workflow/workflow.xml
This change to the XML fixes the observed problem with the post-functions on the 'create' transition.
FYI @aibaars @Daverlo
=> Fix typo in workflow xml that was causing corrupt post function

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/util/JiraUtils.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunction.java, src/main/resources/js/lgtm-addon.js
This approach will always work, regardless of whether the scheme in question is used my multiple projects. (I think including _both_ sets of instructions complicates things unnecessarily...)
Also adds a bit more information to an error message associated with retrieval of the custom field.
=> Change manual migration message to indicate use of workflow schemes page

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/config/Config.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/TestLgtmServletBase.java
The refactoring introduced a null pointer exception. It turns out that the `Properties` class does not permit `null` values and throws a `NullPointerException` if a `null` value is put into it. Instead we should remove the entry.
In addition this PR fixes some warnings that were left-over after the refactoring.
@Daverlo
=> Fix NullPointerException and warnings

src/main/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunctionFactory.java, src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties, src/main/resources/templates/postfunctions/lgtm-issue-link.vm, src/main/resources/workflow/workflow.xml, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunctionTest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
A post-function that create a renote issue link that links to the alert
on LGTM that caused the issue ticket.
See also:
https://developer.atlassian.com/server/jira/platform/creating-remote-issue-links/
=> Add remote issue links to tickets

pom.xml, src/main/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunction.java, src/test/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunctionTest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
Apparently webwork/pell-multipart-request used to be in the Atlassian 3rdparty repository, but it no longer is. The mulesoft repository still contains it, so adding it to the pom file.
=> Add repository containing webwork/pell-multipart-request dependency

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/Request.java, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask5AddSetLabelsFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmSetLabelsFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmSetLabelsFunctionFactory.java, src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties, src/main/resources/templates/postfunctions/lgtm-set-labels-input.vm, src/main/resources/templates/postfunctions/lgtm-set-labels.vm, src/main/resources/workflow/workflow.xml, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunctionTest.java, src/test/java/com/semmle/jira/addon/workflow/LgtmSetLabelsFunctionTest.java, src/test/java/com/semmle/jira/addon/workflow/LgtmSeverityPriorityFunctionTest.java
This pull request adds a post-function that populates issue ticket labels based on LGTM alert properties.
The following properties can be included as labels:
* project name
* query identifier
* query language
* query tags
Previously adding the project name as an issue ticket label was hard-coded. This is no longer the case. To maintain backwards compatibility the SetLabels post function is inserted into the existing workflow using a migration with the "set project name as label" toggle set to `true`.
=> Add post function that sets issue labels based on query metadata

pom.xml, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask6UpdateConfig.java, src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties
Prepend LGTM Transition notification with "advanced". This should make it more clear that users should normally not configure that post function themselves.
In addition bump the version number.
@Daverlo
=> Prepend LGTM Transition notification with "advanced"
