src/main/java/com/semmle/jira/addon/config/ProcessedConfig.java
=> Fix possibles NPEs when creating ProcessedConfig

src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/TestValidateRequest.java
=> Revert matchers, for compatibility when testing older Jira versions

.travis.yml
=> Add a basic functioning travis.yml

src/main/resources/js/lgtm-addon.js
=> Load priorities when there is no priorityscheme

.gitignore, format.sh, src/test/java/com/semmle/jira/addon/Utils/Util.java
=> Add code formating script

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java
Before we tried to find a suitable transition by looking
at the set of actions that end in a target state and select
one that starts in the current state. However, some transitions
have a special source state 'all' which means they can be applied
always. This caused a failure as the comparison between the source
state and the current state would fail.
There are many other reasons why an action could fail, therefore
it seems better to simply take the list of possible actions that
end in the target state and ask the SDK to validate them against
the current state of the issue. If the validation succeeds we perform
the transition.
=> Change implementation of applyTransition

pom.xml, src/main/java/com/semmle/jira/addon/config/init/PluginEnabledHandler.java
=> Create 'Lgtm Alert' issue type

src/main/resources/admin.vm, src/main/resources/js/lgtm-addon.js
=> Remove the option to select an issue type

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/config/ProcessedConfig.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestValidateRequest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
Add checks on validity of IssueType when loading add-on config.
FYI @Daverlo @aibaars
=> Validate issue type

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java
=> Format code

src/main/java/com/semmle/jira/addon/config/Config.java, src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/java/com/semmle/jira/addon/config/ProcessedConfig.java, src/main/resources/js/lgtm-addon.js, src/test/java/com/semmle/jira/addon/TestValidateRequest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
=> Remove unnecessary status info from the config

pom.xml
=> Version Bump to 0.2.0

src/main/java/com/semmle/jira/addon/Request.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunctionFactory.java, src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties, src/main/resources/templates/postfunctions/lgtm-dismiss-alert-input.vm, src/main/resources/templates/postfunctions/lgtm-dismiss-alert.vm, src/main/resources/templates/postfunctions/lgtm-transition-notification-input.vm, src/main/resources/templates/postfunctions/lgtm-transition-notification.vm, src/main/resources/workflow/workflow.xml, src/test/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunctionTest.java
Rename LgtmDismissAlert to LgtmTransitionNotificationFunction and improve the UI for configuring the transition.
@nickfyson
=> Refactor LgtmDismissAlert function

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/config/Config.java, src/main/java/com/semmle/jira/addon/config/ProcessedConfig.java, src/main/resources/admin.vm, src/main/resources/js/lgtm-addon.js, src/main/resources/lgtm-addon.properties, src/test/java/com/semmle/jira/addon/TestValidateRequest.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
This PR removes the 'priority' config option, as this same functionality can be addressed by the user with standard Jira features.
FYI @Daverlo @aibaars
=> Remove priority configuration option

src/main/java/com/semmle/jira/addon/config/init/PluginEnabledHandler.java
=> Check if the workflow exists before trying to create it

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java
It looks like we forgot to check that the issue was successfully created.
@Daverlo
=> Handle issue creation errors

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java
This PR re-adds the project label on creation of new tickets.
=> Add project slug as label to new issues

src/main/java/com/semmle/jira/addon/util/JiraUtils.java
This PR fixes a check to prevent duplication of custom fields.
FYI @aibaars
=> Fix string comparison in creation of custom field

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
=> Set labels directly on issue

pom.xml, src/main/java/com/semmle/jira/addon/config/AdminServlet.java, src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask1CreateIssueType.java, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask2CreateWorkflow.java, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask3ConfigMigration.java, src/main/java/com/semmle/jira/addon/config/upgrades/UpgradeTask4CreateConfigKeyField.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/TestValidateRequest.java
=> Fix some warnings

src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/java/com/semmle/jira/addon/util/JiraUtils.java, src/main/resources/js/lgtm-addon.js, src/test/java/it/com/semmle/jira/addon/IntegrationTest.java
If a project uses the system default workflow scheme then we can't configure it, because system schemes are not modifiable.
This PR creates a new scheme in this case and assigns it to the project.
@Daverlo
=> Improve workflow scheme configuration

pom.xml, src/main/java/com/semmle/jira/addon/Request.java, src/main/java/com/semmle/jira/addon/workflow/LgtmSeverityPriorityFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmSeverityPriorityFunctionFactory.java, src/main/resources/atlassian-plugin.xml, src/main/resources/lgtm-addon.properties, src/main/resources/templates/postfunctions/lgtm-severity-priority-input.vm, src/main/resources/templates/postfunctions/lgtm-severity-priority.vm, src/main/resources/workflow/workflow.xml, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunctionTest.java, src/test/java/com/semmle/jira/addon/workflow/LgtmSeverityPriorityFunctionTest.java
This pull request adds a post function for setting the issue priority based on alert query severity.
@Daverlo
=> Post function that sets issue priority based on alert query severity

src/main/java/com/semmle/jira/addon/LgtmServlet.java, src/main/java/com/semmle/jira/addon/Request.java, src/main/java/com/semmle/jira/addon/config/AdminServlet.java, src/main/java/com/semmle/jira/addon/config/ConfigResource.java, src/main/java/com/semmle/jira/addon/util/JiraUtils.java, src/main/java/com/semmle/jira/addon/util/workflow/WorkflowUtils.java, src/main/java/com/semmle/jira/addon/workflow/CheckResolutionFunction.java, src/main/java/com/semmle/jira/addon/workflow/ComparisonOperator.java, src/main/java/com/semmle/jira/addon/workflow/LgtmIssueLinkFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunction.java, src/main/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunctionFactory.java, src/main/java/com/semmle/jira/addon/workflow/ResolutionCondition.java, src/main/java/com/semmle/jira/addon/workflow/ResolutionValidator.java, src/test/java/com/semmle/jira/addon/TestApplyTransition.java, src/test/java/com/semmle/jira/addon/TestCreateIssue.java, src/test/java/com/semmle/jira/addon/TestValidateRequest.java, src/test/java/com/semmle/jira/addon/workflow/LgtmTransitionNotificationFunctionTest.java, src/test/java/com/semmle/jira/addon/workflow/ResolutionValidatorTest.java
=> Fix Eclipse JDT compiler warnings
